### ISSUE TITLE
关于 Modal 的一些细节问题

### ISSUE THREAD

**Issue by baimsg** [cgspine/emo-public#8]
由于 Modal 的显示方法 fun View.emoDialog() 这样的实现方式没有@Composable注解所以当内容已经是显示状态时，状态发生变化以后，已经显示的
Modal 无法响应重组，比如背景颜色无法根据系统变化夜间模式发生重组变化， 这种有什么解决办法吗？还是这样设计就无法做到那种效果

**Comment by cgspine** [comment]
modal 显示的内容在一个独立的 ComposeTree 里，所以你也需要对内容像正常界面一样进行 Theme 的包裹，emoDialog 提供了 themeProvider 参数，就是给你用作 theme 包裹的。

**Comment by baimsg** [comment]
确实👍
